<?php

use Illuminate\Database\Seeder;

class AttendeesTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {


        \DB::table('attendees')->delete();

        \DB::table('attendees')->insert(array (
            0 =>
            array (
                'id' => 1,
                'title' => 'Mr.',
                'first_name' => 'Abdulganiu ',
                'last_name' => 'Ibrahim ',
                'preferred_nickname' => 'Ibraa',
                'email' => 'ibraa4@yahoo.com',
                'gender' => 'Male',
                't_shirt' => '43',
                'contact_number' => '2348045219897',
                'altternate_number' => '1',
                'submitted_date' => '5/7/21 13:59',
                'qr_code' => NULL,
                'status' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            1 =>
            array (
                'id' => 2,
                'title' => 'Mr.',
                'first_name' => 'Gert',
                'last_name' => 'Nel',
                'preferred_nickname' => 'Gert',
                'email' => 'gert.nel@kensingtondistillers.com',
                'gender' => 'Male',
                't_shirt' => '3XL',
                'contact_number' => '27836322172',
                'altternate_number' => '',
                'submitted_date' => '5/5/21 23:02',
                'qr_code' => NULL,
                'status' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            2 =>
            array (
                'id' => 3,
                'title' => 'Mr.',
                'first_name' => 'Modupe',
                'last_name' => 'Majekodunmi',
                'preferred_nickname' => 'Mo',
                'email' => 'moru_majek@yahoo.com',
                'gender' => 'Male',
                't_shirt' => 'Large',
                'contact_number' => '2348028645009',
                'altternate_number' => '1',
                'submitted_date' => '5/4/21 11:13',
                'qr_code' => NULL,
                'status' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            3 =>
            array (
                'id' => 4,
                'title' => 'Mr.',
                'first_name' => 'Jethro',
                'last_name' => 'Sansom',
                'preferred_nickname' => 'Jethro',
                'email' => 'jethro@kensingtondistillers.co.uk',
                'gender' => 'Male',
                't_shirt' => 'Large',
                'contact_number' => '2348143030777',
                'altternate_number' => '1',
                'submitted_date' => '4/13/21 17:49',
                'qr_code' => NULL,
                'status' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            4 =>
            array (
                'id' => 5,
                'title' => 'Mr.',
                'first_name' => 'Christian',
                'last_name' => 'Stenslunde',
                'preferred_nickname' => 'John',
                'email' => 'stef.klaus@trumanandorange.com',
                'gender' => 'Male',
                't_shirt' => 'XX-Large',
                'contact_number' => '27829241570',
                'altternate_number' => '27824571239',
                'submitted_date' => '4/12/21 8:56',
                'qr_code' => NULL,
                'status' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            5 =>
            array (
                'id' => 6,
                'title' => 'Mr.',
                'first_name' => 'Aiji ',
                'last_name' => 'Raymond',
                'preferred_nickname' => 'Ray',
                'email' => 'raymondaiji38@yahoo.com',
                'gender' => 'Male',
                't_shirt' => 'XXL',
                'contact_number' => '18037690936',
                'altternate_number' => '19062840660',
                'submitted_date' => '4/9/21 13:34',
                'qr_code' => NULL,
                'status' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            6 =>
            array (
                'id' => 7,
                'title' => 'Mr.',
                'first_name' => 'Owen',
                'last_name' => 'Gibbs',
                'preferred_nickname' => 'Owen',
                'email' => 'stef.klaus@trumanandorange.com',
                'gender' => 'Male',
                't_shirt' => 'X-large',
                'contact_number' => '27662861734',
                'altternate_number' => '27824571239',
                'submitted_date' => '4/9/21 12:17',
                'qr_code' => NULL,
                'status' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            7 =>
            array (
                'id' => 8,
                'title' => 'Mr.',
                'first_name' => 'Rowan',
                'last_name' => 'Leibbrandt',
                'preferred_nickname' => 'Rowan',
                'email' => 'stef.klaus@trumanandorange.com',
                'gender' => 'Male',
                't_shirt' => 'X-large',
                'contact_number' => '27760917234',
                'altternate_number' => '27760915588',
                'submitted_date' => '4/9/21 12:02',
                'qr_code' => NULL,
                'status' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            8 =>
            array (
                'id' => 9,
                'title' => 'Mrs.',
                'first_name' => 'Emmanuel ',
                'last_name' => 'Blessing ',
                'preferred_nickname' => 'Kweke ',
                'email' => 'emmanuelblessing959@gmail.com',
                'gender' => 'Female',
                't_shirt' => 'XL',
                'contact_number' => '23409062537846',
                'altternate_number' => '23408109901970',
                'submitted_date' => '4/9/21 9:54',
                'qr_code' => NULL,
                'status' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            9 =>
            array (
                'id' => 10,
                'title' => 'Mr.',
                'first_name' => 'Peter',
                'last_name' => 'Ogugua',
                'preferred_nickname' => 'Papi',
                'email' => 'peter.ogugua@kensingtondistillers.co.uk',
                'gender' => 'Male',
                't_shirt' => 'Xx large',
                'contact_number' => '8099447628',
                'altternate_number' => '8099447628',
                'submitted_date' => '4/9/21 9:43',
                'qr_code' => NULL,
                'status' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            10 =>
            array (
                'id' => 11,
                'title' => 'Mr.',
                'first_name' => 'Inalegwu',
                'last_name' => 'Abel',
                'preferred_nickname' => 'Inans',
                'email' => 'biginans@yahoo.com',
                'gender' => 'Male',
                't_shirt' => 'XXL',
                'contact_number' => '17032162692',
                'altternate_number' => '19062538818',
                'submitted_date' => '4/9/21 8:44',
                'qr_code' => NULL,
                'status' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            11 =>
            array (
                'id' => 12,
                'title' => 'Ms.',
                'first_name' => 'ESTHER',
                'last_name' => 'AGBAKEDIO',
                'preferred_nickname' => 'OMOIYABEJI',
                'email' => 'esther.agbakedio@kensingtondistillers.co.uk',
                'gender' => 'Female',
                't_shirt' => 'LARGE',
                'contact_number' => '2347037953327',
                'altternate_number' => '1',
                'submitted_date' => '4/9/21 8:18',
                'qr_code' => NULL,
                'status' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            12 =>
            array (
                'id' => 13,
                'title' => 'Mr.',
                'first_name' => 'Johnson ',
                'last_name' => 'Ezike ',
                'preferred_nickname' => 'Jigga',
                'email' => 'chukajohnson4real@yahoo.com',
                'gender' => 'Male',
                't_shirt' => 'X large',
                'contact_number' => '2349062844574',
                'altternate_number' => '2348063260547',
                'submitted_date' => '4/9/21 6:30',
                'qr_code' => NULL,
                'status' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            13 =>
            array (
                'id' => 14,
                'title' => 'Mr.',
                'first_name' => 'UBONG ',
                'last_name' => 'INEME',
                'preferred_nickname' => 'CROWN ',
                'email' => 'inem.ubong@kensingtondistillers.co.uk',
                'gender' => 'Male',
                't_shirt' => 'XXL',
                'contact_number' => '2349062537776',
                'altternate_number' => '2349036002007',
                'submitted_date' => '4/8/21 23:02',
                'qr_code' => NULL,
                'status' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            14 =>
            array (
                'id' => 15,
                'title' => 'Mr.',
                'first_name' => 'AJAY',
                'last_name' => 'MALHOTRA',
                'preferred_nickname' => 'AJAY',
                'email' => 'ajay@kensingtondistillers.co.uk',
                'gender' => 'Male',
                't_shirt' => '2XL',
                'contact_number' => '2349060008599',
                'altternate_number' => '1',
                'submitted_date' => '4/8/21 19:24',
                'qr_code' => NULL,
                'status' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            15 =>
            array (
                'id' => 16,
                'title' => 'Mr.',
                'first_name' => 'Rudolf ',
                'last_name' => 'Ejuone ',
                'preferred_nickname' => 'Rudolphine.',
                'email' => 'rudolf@kensingtondistillers.co.uk',
                'gender' => 'Male',
                't_shirt' => 'Large ',
                'contact_number' => '9062550120',
                'altternate_number' => '8099776286',
                'submitted_date' => '4/8/21 18:55',
                'qr_code' => NULL,
                'status' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            16 =>
            array (
                'id' => 17,
                'title' => 'Mr.',
                'first_name' => 'Jonathan ',
                'last_name' => 'Folorunsho Adabara ',
                'preferred_nickname' => 'FJ',
                'email' => 'jonathanadabaraf@yahoo.com',
                'gender' => 'Male',
                't_shirt' => 'XL',
                'contact_number' => '2349062550114',
                'altternate_number' => '2348064533075',
                'submitted_date' => '4/8/21 18:04',
                'qr_code' => NULL,
                'status' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            17 =>
            array (
                'id' => 18,
                'title' => 'Mr.',
                'first_name' => 'Victor',
                'last_name' => 'Umoru',
                'preferred_nickname' => 'Vakes',
                'email' => 'victor.umoru@kensingtondistillers.co.uk',
                'gender' => 'Male',
                't_shirt' => 'M',
                'contact_number' => '2349062826144',
                'altternate_number' => '2349062826144',
                'submitted_date' => '4/8/21 17:16',
                'qr_code' => NULL,
                'status' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            18 =>
            array (
                'id' => 19,
                'title' => 'Mr.',
                'first_name' => 'Sunday ',
                'last_name' => 'Achukwu ',
                'preferred_nickname' => 'achuks',
                'email' => 'sunedeh34@gmail.com',
                'gender' => 'Male',
                't_shirt' => 'Medium ',
                'contact_number' => '2348039654541',
                'altternate_number' => '2349062550112',
                'submitted_date' => '4/8/21 16:28',
                'qr_code' => NULL,
                'status' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            19 =>
            array (
                'id' => 20,
                'title' => 'Mr.',
                'first_name' => 'INNOCENT ',
                'last_name' => 'EZE',
                'preferred_nickname' => 'INNO',
                'email' => 'innocent.eze@kensingtondistillers.co.uk',
                'gender' => 'Male',
                't_shirt' => 'Xl',
                'contact_number' => '2349062840661',
                'altternate_number' => '2348035369217',
                'submitted_date' => '4/8/21 14:56',
                'qr_code' => NULL,
                'status' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            20 =>
            array (
                'id' => 21,
                'title' => 'Mr.',
                'first_name' => 'MARIO',
                'last_name' => 'IDISI',
                'preferred_nickname' => 'MARIAYO',
                'email' => 'mario.idisi@kensingtondistillers.co.uk',
                'gender' => 'Male',
                't_shirt' => 'XL',
                'contact_number' => '2349062538839',
                'altternate_number' => '2347088338474',
                'submitted_date' => '4/8/21 14:45',
                'qr_code' => NULL,
                'status' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            21 =>
            array (
                'id' => 22,
                'title' => 'Ms.',
                'first_name' => 'Anne',
                'last_name' => 'Benjamin ',
                'preferred_nickname' => 'AJ',
                'email' => 'benjaminanne2@gmail.com',
                'gender' => 'Female',
            't_shirt' => 'Medium (UK Size 8)',
                'contact_number' => '23409062550113',
                'altternate_number' => '1',
                'submitted_date' => '4/8/21 14:34',
                'qr_code' => NULL,
                'status' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            22 =>
            array (
                'id' => 23,
                'title' => 'Mr.',
                'first_name' => 'Stephen ',
                'last_name' => 'Ordu ',
                'preferred_nickname' => 'Steve',
                'email' => 'Stephen.chibuzor@kensingtondistillers.co.uk',
                'gender' => 'Male',
                't_shirt' => 'XXL',
                'contact_number' => '2347065150524',
                'altternate_number' => '2347065150524',
                'submitted_date' => '4/8/21 14:08',
                'qr_code' => NULL,
                'status' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            23 =>
            array (
                'id' => 24,
                'title' => 'Mr.',
                'first_name' => 'Emeka ',
                'last_name' => ' UMUNNAKWE ',
                'preferred_nickname' => 'Henry ',
                'email' => 'henry.umunnakwu@kesington.co.uk',
                'gender' => 'Male',
                't_shirt' => 'Xl',
                'contact_number' => '8062811906',
                'altternate_number' => '9030425292',
                'submitted_date' => '4/8/21 13:50',
                'qr_code' => NULL,
                'status' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            24 =>
            array (
                'id' => 25,
                'title' => 'Mr.',
                'first_name' => 'KENNETH',
                'last_name' => 'OKO',
                'preferred_nickname' => 'Hon Ken',
                'email' => 'knnthoko@gmail.com',
                'gender' => 'Male',
                't_shirt' => 'Xxl',
                'contact_number' => '2348035608816',
                'altternate_number' => '2349062537240',
                'submitted_date' => '4/8/21 13:50',
                'qr_code' => NULL,
                'status' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            25 =>
            array (
                'id' => 26,
                'title' => 'Ms.',
                'first_name' => 'Chinelo',
                'last_name' => 'Ezebuka',
                'preferred_nickname' => 'Naylo',
                'email' => 'chineloezebuka@yahoo.com',
                'gender' => 'Female',
                't_shirt' => 'Medium',
                'contact_number' => '2348120064094',
                'altternate_number' => '2348039257021',
                'submitted_date' => '4/8/21 13:48',
                'qr_code' => NULL,
                'status' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            26 =>
            array (
                'id' => 27,
                'title' => 'Choose One',
                'first_name' => 'Usen',
                'last_name' => 'Udoh',
                'preferred_nickname' => 'Useny',
                'email' => 'usenjames60@yahoo.com',
                'gender' => 'Male',
                't_shirt' => 'XL',
                'contact_number' => '2348036068164',
                'altternate_number' => '1',
                'submitted_date' => '4/8/21 13:47',
                'qr_code' => NULL,
                'status' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            27 =>
            array (
                'id' => 28,
                'title' => 'Ms.',
                'first_name' => 'Uwem ',
                'last_name' => 'Thompson ',
                'preferred_nickname' => 'Mary ',
                'email' => 'mary.thompson@kensingtondistillers.co.uk',
                'gender' => 'Female',
                't_shirt' => 'Medium',
                'contact_number' => '2349062040030',
                'altternate_number' => '2348062263305',
                'submitted_date' => '4/8/21 13:34',
                'qr_code' => NULL,
                'status' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            28 =>
            array (
                'id' => 29,
                'title' => 'Ms.',
                'first_name' => 'TEMITOPE',
                'last_name' => 'DAWODU',
                'preferred_nickname' => 'TP2',
                'email' => 'temitope.dawodu@kensingtondistillers.co.uk',
                'gender' => 'Female',
                't_shirt' => 'XL',
                'contact_number' => '2349062550116',
                'altternate_number' => '2348076109810',
                'submitted_date' => '4/8/21 13:26',
                'qr_code' => NULL,
                'status' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            29 =>
            array (
                'id' => 30,
                'title' => 'Choose One',
                'first_name' => 'Godwin',
                'last_name' => 'Oche',
                'preferred_nickname' => 'NA GODWIN',
                'email' => 'godwin.oche@kensingtondistillers.co.uk',
                'gender' => 'Male',
                't_shirt' => 'L',
                'contact_number' => '2348064742009',
                'altternate_number' => '1',
                'submitted_date' => '4/8/21 13:24',
                'qr_code' => NULL,
                'status' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            30 =>
            array (
                'id' => 31,
                'title' => 'Mr.',
                'first_name' => 'Gabriel ',
                'last_name' => 'Oniya',
                'preferred_nickname' => 'Gabis',
                'email' => 'Gabriel.oniya@kensingtondistillers.co.uk',
                'gender' => 'Male',
                't_shirt' => 'Large',
                'contact_number' => '9062550109',
                'altternate_number' => '7068134388',
                'submitted_date' => '4/8/21 13:18',
                'qr_code' => NULL,
                'status' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            31 =>
            array (
                'id' => 32,
                'title' => 'Ms.',
                'first_name' => 'GRACE',
                'last_name' => 'MOMMA',
                'preferred_nickname' => 'NENA',
                'email' => 'grace@kensingtondistillers.co.uk',
                'gender' => 'Female',
                't_shirt' => '12',
                'contact_number' => '2349062550111',
                'altternate_number' => '2348144487900',
                'submitted_date' => '4/8/21 13:15',
                'qr_code' => NULL,
                'status' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            32 =>
            array (
                'id' => 33,
                'title' => 'Mr.',
                'first_name' => 'Ikenna',
                'last_name' => 'Ali',
                'preferred_nickname' => 'Aikman',
                'email' => 'ikenna.ali@kensingtondistillers.com',
                'gender' => 'Male',
                't_shirt' => 'Large',
                'contact_number' => '2348064911987',
                'altternate_number' => '234',
                'submitted_date' => '4/8/21 12:54',
                'qr_code' => NULL,
                'status' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            33 =>
            array (
                'id' => 34,
                'title' => 'Mr.',
                'first_name' => 'Tubosun',
                'last_name' => 'Akeju',
                'preferred_nickname' => 'TA',
                'email' => 'Ta@seid.in',
                'gender' => 'Male',
                't_shirt' => 'medium',
                'contact_number' => '2348037276206',
                'altternate_number' => '1',
                'submitted_date' => '4/8/21 12:03',
                'qr_code' => NULL,
                'status' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            34 =>
            array (
                'id' => 35,
                'title' => 'Mr.',
                'first_name' => 'Nnamdi',
                'last_name' => 'Dike',
                'preferred_nickname' => 'Nnamddyke',
                'email' => 'nnamdi.dike@kensingtondistillers.co.uk',
                'gender' => 'Male',
                't_shirt' => 'Large',
                'contact_number' => '2349062550108',
                'altternate_number' => '1',
                'submitted_date' => '4/8/21 11:27',
                'qr_code' => NULL,
                'status' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            35 =>
            array (
                'id' => 36,
                'title' => 'Mr.',
                'first_name' => 'Joseph',
                'last_name' => 'Sanyaolu',
                'preferred_nickname' => 'Cash',
                'email' => 'joseph@fountrands.com',
                'gender' => 'Male',
                't_shirt' => 'Medium',
                'contact_number' => '2348038165555',
                'altternate_number' => '2348038165555',
                'submitted_date' => '4/8/21 11:09',
                'qr_code' => NULL,
                'status' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            36 =>
            array (
                'id' => 37,
                'title' => 'Mr.',
                'first_name' => 'Akintunde ',
                'last_name' => 'Marinho',
                'preferred_nickname' => 'MR MARINE ',
                'email' => 'a.marinho@utopiamedia-group.com',
                'gender' => 'Male',
                't_shirt' => 'M',
                'contact_number' => '2348182799268',
                'altternate_number' => '2348033150610',
                'submitted_date' => '4/8/21 9:32',
                'qr_code' => NULL,
                'status' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            37 =>
            array (
                'id' => 38,
                'title' => 'Mr.',
                'first_name' => 'Tolu',
                'last_name' => 'Olokun',
                'preferred_nickname' => 'Fountrands',
                'email' => 'tolu@fountrands.com',
                'gender' => 'Male',
                't_shirt' => 'XL',
                'contact_number' => '2348080805101',
                'altternate_number' => '1',
                'submitted_date' => '4/8/21 9:02',
                'qr_code' => NULL,
                'status' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            38 =>
            array (
                'id' => 39,
                'title' => 'Mr.',
                'first_name' => 'Johnson',
                'last_name' => 'Ekwere ',
                'preferred_nickname' => 'Jigga',
                'email' => 'johnson.ekwere@kensingtondistillers.co.uk',
                'gender' => 'Male',
                't_shirt' => 'XL',
                'contact_number' => '2349062826146',
                'altternate_number' => '2348133294744',
                'submitted_date' => '4/8/21 6:56',
                'qr_code' => NULL,
                'status' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            39 =>
            array (
                'id' => 40,
                'title' => 'Mr.',
                'first_name' => 'Faith ',
                'last_name' => 'Otalor ',
                'preferred_nickname' => 'Otalor ',
                'email' => 'Otalorfaith01@gmail.com',
                'gender' => 'Male',
                't_shirt' => 'X large',
                'contact_number' => '2347035840941',
                'altternate_number' => '234',
                'submitted_date' => '4/7/21 18:54',
                'qr_code' => NULL,
                'status' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            40 =>
            array (
                'id' => 41,
                'title' => 'Mrs.',
                'first_name' => 'Treasure',
                'last_name' => 'Patrick',
                'preferred_nickname' => 'Tesoro',
                'email' => 'treasure.patrick@kensingtondistillers.co.uk',
                'gender' => 'Female',
                't_shirt' => 'XL',
                'contact_number' => '2348066466008',
                'altternate_number' => '',
                'submitted_date' => '4/7/21 16:31',
                'qr_code' => NULL,
                'status' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            41 =>
            array (
                'id' => 42,
                'title' => 'Mr.',
                'first_name' => 'Darryl',
                'last_name' => 'Denton',
                'preferred_nickname' => 'The CAT',
                'email' => 'darryldentondd@gmail.com',
                'gender' => 'Male',
                't_shirt' => 'XXXL',
                'contact_number' => '+27 082 3811014',
                'altternate_number' => '1',
                'submitted_date' => '4/7/21 14:03',
                'qr_code' => NULL,
                'status' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            42 =>
            array (
                'id' => 43,
                'title' => 'Mr.',
                'first_name' => 'OPEYEMI',
                'last_name' => 'DAIRO',
                'preferred_nickname' => 'Opsy',
                'email' => 'dirandairo@gmail.com',
                'gender' => 'Male',
                't_shirt' => 'Large',
                'contact_number' => '2348038077989',
                'altternate_number' => '1',
                'submitted_date' => '4/7/21 8:09',
                'qr_code' => NULL,
                'status' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            43 =>
            array (
                'id' => 44,
                'title' => 'Mr.',
                'first_name' => 'Uche',
                'last_name' => 'Ogbonna ',
                'preferred_nickname' => 'Giant',
                'email' => 'Ogbonnauche2010@gmail.com',
                'gender' => 'Male',
                't_shirt' => 'XL',
                'contact_number' => '2347038759207',
                'altternate_number' => '2348063484566',
                'submitted_date' => '4/7/21 4:02',
                'qr_code' => NULL,
                'status' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            44 =>
            array (
                'id' => 45,
                'title' => 'Mr.',
                'first_name' => 'Azubuike',
                'last_name' => 'Johnson',
                'preferred_nickname' => 'Jay',
                'email' => 'azubuikejohnson84@gmail.com',
                'gender' => 'Male',
                't_shirt' => 'Large ',
                'contact_number' => '2348035850247',
                'altternate_number' => '1',
                'submitted_date' => '4/6/21 21:57',
                'qr_code' => NULL,
                'status' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            45 =>
            array (
                'id' => 46,
                'title' => 'Mr.',
                'first_name' => 'Faith',
                'last_name' => 'Otalor',
                'preferred_nickname' => 'Otalor',
                'email' => 'otalorfaith01@gmail.com',
                'gender' => 'Male',
                't_shirt' => 'XL',
                'contact_number' => '2347035840941',
                'altternate_number' => '1',
                'submitted_date' => '4/6/21 21:02',
                'qr_code' => NULL,
                'status' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            46 =>
            array (
                'id' => 47,
                'title' => 'Mr.',
                'first_name' => 'Shawn',
                'last_name' => 'Okagbue',
                'preferred_nickname' => 'Shawnkabz',
                'email' => 'shawnokagbue@gmail.com',
                'gender' => 'Male',
                't_shirt' => 'XXL',
                'contact_number' => '23407065130670',
                'altternate_number' => '1',
                'submitted_date' => '4/6/21 20:56',
                'qr_code' => NULL,
                'status' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            47 =>
            array (
                'id' => 48,
                'title' => 'Mr.',
                'first_name' => 'Uche',
                'last_name' => 'Ogbonna ',
                'preferred_nickname' => 'Giant',
                'email' => 'Ogbonnauche2010@gmail.com',
                'gender' => 'Male',
                't_shirt' => 'XL',
                'contact_number' => '2347038759207',
                'altternate_number' => '2348163484566',
                'submitted_date' => '4/6/21 20:30',
                'qr_code' => NULL,
                'status' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            48 =>
            array (
                'id' => 49,
                'title' => 'Mr.',
                'first_name' => 'Abiodun',
                'last_name' => 'Awoyale',
                'preferred_nickname' => 'Abbey',
                'email' => 'abiodunawoyale@yahoo.com',
                'gender' => 'Male',
                't_shirt' => '16, XL',
                'contact_number' => '+234 8033765649',
                'altternate_number' => '2348033765649',
                'submitted_date' => '4/6/21 16:10',
                'qr_code' => NULL,
                'status' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            49 =>
            array (
                'id' => 50,
                'title' => 'Mrs.',
                'first_name' => 'Olaite',
                'last_name' => 'Osifeso',
                'preferred_nickname' => 'LT',
                'email' => 'olaite.osifeso@gmail.com',
                'gender' => 'Female',
                't_shirt' => 'Large',
                'contact_number' => '2348062353969',
                'altternate_number' => '1',
                'submitted_date' => '4/6/21 9:44',
                'qr_code' => NULL,
                'status' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            50 =>
            array (
                'id' => 51,
                'title' => 'Mr.',
                'first_name' => 'Johnson ',
                'last_name' => 'Ezike',
                'preferred_nickname' => 'JIGGA',
                'email' => 'chukajohnson4real@yahoo.com',
                'gender' => 'Male',
                't_shirt' => 'X large',
                'contact_number' => '2349062844574',
                'altternate_number' => '2348063260547',
                'submitted_date' => '4/6/21 9:40',
                'qr_code' => NULL,
                'status' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            51 =>
            array (
                'id' => 52,
                'title' => 'Mrs.',
                'first_name' => 'Bukola ',
                'last_name' => 'Jimoh',
                'preferred_nickname' => 'Youngolash ',
                'email' => 'bukola.olaosebikan@kensingtondistillers.co.uk',
                'gender' => 'Female',
                't_shirt' => 'XL ',
                'contact_number' => '2349062537239',
                'altternate_number' => '2348038712261',
                'submitted_date' => '4/6/21 5:59',
                'qr_code' => NULL,
                'status' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            52 =>
            array (
                'id' => 53,
                'title' => 'Mr.',
                'first_name' => 'Emeka',
                'last_name' => 'Okonkwo',
                'preferred_nickname' => 'Emekus',
                'email' => 'emeka.okonkwo@kensingtondistillers.co.uk',
                'gender' => 'Male',
                't_shirt' => 'L',
                'contact_number' => '2349062826154',
                'altternate_number' => '2348032804881',
                'submitted_date' => '4/5/21 22:24',
                'qr_code' => NULL,
                'status' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            53 =>
            array (
                'id' => 54,
                'title' => 'Mr.',
                'first_name' => 'Aditya ',
                'last_name' => 'Malhotra',
                'preferred_nickname' => 'Addy',
                'email' => 'addy@kensingtondistillers.co.uk',
                'gender' => 'Male',
                't_shirt' => 'xl',
                'contact_number' => '2349062550123',
                'altternate_number' => '1',
                'submitted_date' => '4/5/21 19:10',
                'qr_code' => NULL,
                'status' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            54 =>
            array (
                'id' => 55,
                'title' => 'Mr.',
                'first_name' => 'Adeshina ',
                'last_name' => 'Tiamiyu',
                'preferred_nickname' => 'Shyner',
                'email' => 'tiamiyu.adeshina@kensingtondistillers.co.uk',
                'gender' => 'Male',
                't_shirt' => 'Large',
                'contact_number' => '2349062535555',
                'altternate_number' => '1',
                'submitted_date' => '4/5/21 17:27',
                'qr_code' => NULL,
                'status' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            55 =>
            array (
                'id' => 56,
                'title' => 'Mr.',
                'first_name' => 'Johannes',
                'last_name' => 'Nel',
                'preferred_nickname' => 'Hannes',
                'email' => 'Johannes.nel@kensingtondistillers.co.uk',
                'gender' => 'Male',
                't_shirt' => 'Medium',
                'contact_number' => '2349062826155',
                'altternate_number' => '1',
                'submitted_date' => '4/5/21 11:28',
                'qr_code' => NULL,
                'status' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            56 =>
            array (
                'id' => 57,
                'title' => 'Mr.',
                'first_name' => 'Odemwingie ',
                'last_name' => 'Omoregie ',
                'preferred_nickname' => 'Evi',
                'email' => 'odemwingie@kensingtondistillers.co.uk',
                'gender' => 'Male',
                't_shirt' => 'Large',
                'contact_number' => '2349062550115',
                'altternate_number' => '2348064848634',
                'submitted_date' => '4/5/21 8:31',
                'qr_code' => NULL,
                'status' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            57 =>
            array (
                'id' => 58,
                'title' => 'Mr.',
                'first_name' => 'INNOCENT',
                'last_name' => 'EZE',
                'preferred_nickname' => 'INNO',
                'email' => 'innocent.eze@kensingtondistillers.co.uk',
                'gender' => 'Male',
                't_shirt' => 'XL',
                'contact_number' => '2349062840661',
                'altternate_number' => '2348035369217',
                'submitted_date' => '4/4/21 15:12',
                'qr_code' => NULL,
                'status' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            58 =>
            array (
                'id' => 59,
                'title' => 'Mr.',
                'first_name' => 'Ashwathanarayana Kadur',
                'last_name' => 'Nanjundaiah',
                'preferred_nickname' => 'Ash',
                'email' => 'ash@kensingtondistillers.co.uk',
                'gender' => 'Male',
                't_shirt' => 'Large',
                'contact_number' => '2349062550104',
                'altternate_number' => '2347080383691',
                'submitted_date' => '4/4/21 10:26',
                'qr_code' => NULL,
                'status' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            59 =>
            array (
                'id' => 60,
                'title' => 'Mr.',
                'first_name' => 'Tony ',
                'last_name' => 'Uwabor',
                'preferred_nickname' => 'Tonero',
                'email' => 'tonyuwabor@gmail.com',
                'gender' => 'Male',
                't_shirt' => 'Medium ',
                'contact_number' => '2347069297715',
                'altternate_number' => '1',
                'submitted_date' => '4/3/21 19:48',
                'qr_code' => NULL,
                'status' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            60 =>
            array (
                'id' => 61,
                'title' => 'Mr.',
                'first_name' => 'GREGORY ',
                'last_name' => 'NWANKWO ',
                'preferred_nickname' => 'Greg',
                'email' => 'gnwankwoi@gmail.com',
                'gender' => 'Male',
                't_shirt' => 'XXL',
                'contact_number' => '2348032644407',
                'altternate_number' => '1',
                'submitted_date' => '4/3/21 18:52',
                'qr_code' => NULL,
                'status' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            61 =>
            array (
                'id' => 62,
                'title' => 'Mr.',
                'first_name' => 'Godfrey',
                'last_name' => 'Kanghambo',
                'preferred_nickname' => 'Godfrey',
                'email' => 'godfrey.kanghambo@gmail.com',
                'gender' => 'Male',
                't_shirt' => 'XXL',
                'contact_number' => '2347066876649',
                'altternate_number' => '256752467201',
                'submitted_date' => '4/3/21 15:49',
                'qr_code' => NULL,
                'status' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            62 =>
            array (
                'id' => 63,
                'title' => 'Mr.',
                'first_name' => 'Abiodun',
                'last_name' => 'Ajiborode',
                'preferred_nickname' => 'Lifecoach',
                'email' => 'a.ajiborode@gmail.com',
                'gender' => 'Male',
                't_shirt' => 'Medium',
                'contact_number' => '2348067491460',
                'altternate_number' => '2348067491460',
                'submitted_date' => '4/3/21 14:36',
                'qr_code' => NULL,
                'status' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            63 =>
            array (
                'id' => 64,
                'title' => 'Mr.',
                'first_name' => 'Oddiri',
                'last_name' => 'Felix',
                'preferred_nickname' => 'FK',
                'email' => 'fkoddiri@yahoo.com',
                'gender' => 'Male',
                't_shirt' => 'XL',
                'contact_number' => '2348031348847',
                'altternate_number' => '2348022258740',
                'submitted_date' => '4/3/21 14:21',
                'qr_code' => NULL,
                'status' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            64 =>
            array (
                'id' => 65,
                'title' => 'Mr.',
                'first_name' => 'Bello',
                'last_name' => 'Isaac',
                'preferred_nickname' => 'IBello',
                'email' => 'isaac.bello@kensingtondistillers.co.uk',
                'gender' => 'Male',
                't_shirt' => 'Xl',
                'contact_number' => '2349062826145',
                'altternate_number' => '1',
                'submitted_date' => '4/3/21 14:21',
                'qr_code' => NULL,
                'status' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            65 =>
            array (
                'id' => 66,
                'title' => 'Mr.',
                'first_name' => 'Olabimi ',
                'last_name' => 'Kayode ',
                'preferred_nickname' => 'Kay pompin',
                'email' => 'kayode@kensingtondistillers.co.uk',
                'gender' => 'Male',
                't_shirt' => 'XXL',
                'contact_number' => '2349062550117',
                'altternate_number' => '2349062550117',
                'submitted_date' => '4/3/21 8:59',
                'qr_code' => NULL,
                'status' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            66 =>
            array (
                'id' => 67,
                'title' => 'Mr.',
                'first_name' => 'Ibrahim',
                'last_name' => 'Ovansa',
                'preferred_nickname' => 'OV',
                'email' => 'ibrahim@kensingtondistillers.co.uk',
                'gender' => 'Male',
                't_shirt' => 'Large',
                'contact_number' => '2348104399944',
                'altternate_number' => '1',
                'submitted_date' => '4/3/21 8:23',
                'qr_code' => NULL,
                'status' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            67 =>
            array (
                'id' => 68,
                'title' => 'Mr.',
                'first_name' => 'Victor',
                'last_name' => 'Umoru',
                'preferred_nickname' => 'Vakes',
                'email' => 'victor.umoru@kensingtondistillers.co.uk',
                'gender' => 'Male',
                't_shirt' => 'M',
                'contact_number' => '2349062826144',
                'altternate_number' => '2349062826144',
                'submitted_date' => '4/2/21 21:30',
                'qr_code' => NULL,
                'status' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            68 =>
            array (
                'id' => 69,
                'title' => 'Mr.',
                'first_name' => 'Okemiri',
                'last_name' => 'Obinna ',
                'preferred_nickname' => 'Deey',
                'email' => 'okemiri.obinna@kengstiondistillers.co.uk',
                'gender' => 'Male',
                't_shirt' => 'Large ',
                'contact_number' => '2349062826152',
                'altternate_number' => '2349062826152',
                'submitted_date' => '4/2/21 17:19',
                'qr_code' => NULL,
                'status' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            69 =>
            array (
                'id' => 70,
                'title' => 'Mrs.',
                'first_name' => 'Medara ',
                'last_name' => 'Ekpenyong ',
                'preferred_nickname' => 'Dara',
                'email' => 'ekpenyong.medara@kensingtondistillers.co.uk',
                'gender' => 'Female',
                't_shirt' => 'Small',
                'contact_number' => '2349062437630',
                'altternate_number' => '2348037616229',
                'submitted_date' => '4/2/21 12:07',
                'qr_code' => NULL,
                'status' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            70 =>
            array (
                'id' => 71,
                'title' => 'Mr.',
                'first_name' => 'Augustine ',
                'last_name' => 'Onyeguili ',
                'preferred_nickname' => 'Austin',
                'email' => 'austin.onyeguili@kensingtondistillers.co.uk',
                'gender' => 'Male',
                't_shirt' => 'L',
                'contact_number' => '2349062550121',
                'altternate_number' => '2348032373219',
                'submitted_date' => '4/2/21 8:47',
                'qr_code' => NULL,
                'status' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            71 =>
            array (
                'id' => 72,
                'title' => 'Mr.',
                'first_name' => 'Kelechi',
                'last_name' => 'Ajoku',
                'preferred_nickname' => 'Mr Kayc',
                'email' => 'kelechi.ajoku@kensingtondistillers.co.uk',
                'gender' => 'Male',
                't_shirt' => 'Large',
                'contact_number' => '2349062826143',
                'altternate_number' => '2348095294702',
                'submitted_date' => '4/2/21 8:01',
                'qr_code' => NULL,
                'status' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            72 =>
            array (
                'id' => 73,
                'title' => 'Mr.',
                'first_name' => 'Inalegwu ',
                'last_name' => 'Abel ',
                'preferred_nickname' => 'Inans',
                'email' => 'biginans@yahoo.com',
                'gender' => 'Male',
                't_shirt' => 'XXL',
                'contact_number' => '17032162692',
                'altternate_number' => '18174209614',
                'submitted_date' => '4/2/21 6:45',
                'qr_code' => NULL,
                'status' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            73 =>
            array (
                'id' => 74,
                'title' => 'Mr.',
                'first_name' => 'Adewale',
                'last_name' => 'Adesanya',
                'preferred_nickname' => 'Giggs ',
                'email' => 'waleadesanya01@gmail.com',
                'gender' => 'Male',
                't_shirt' => 'Medium ',
                'contact_number' => '23409062826157',
                'altternate_number' => '23407032418388',
                'submitted_date' => '4/2/21 0:37',
                'qr_code' => NULL,
                'status' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            74 =>
            array (
                'id' => 75,
                'title' => 'Choose One',
                'first_name' => 'Enivwe',
                'last_name' => 'Ochuko',
                'preferred_nickname' => 'Poke',
                'email' => 'enivwe.ochuko@kensingtondistillers.co.uk',
                'gender' => 'Male',
                't_shirt' => 'XXL',
                'contact_number' => '2349062826153',
                'altternate_number' => '1',
                'submitted_date' => '4/1/21 17:09',
                'qr_code' => NULL,
                'status' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            75 =>
            array (
                'id' => 76,
                'title' => 'Mrs.',
                'first_name' => 'Michael',
                'last_name' => 'Edidiong',
                'preferred_nickname' => 'Eddies',
                'email' => 'edidong.michael@kensingtondistillers.co.uk',
                'gender' => 'Female',
            't_shirt' => 'Large (L)',
                'contact_number' => '2348086995510',
                'altternate_number' => '2349062826151',
                'submitted_date' => '4/1/21 12:49',
                'qr_code' => NULL,
                'status' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            76 =>
            array (
                'id' => 77,
                'title' => 'Mr.',
                'first_name' => 'Nonso ',
                'last_name' => 'Ifesinachukwu ',
                'preferred_nickname' => 'Chinonso',
                'email' => 'nonso.ifesinachukwu@kensingtondistillers.co.uk',
                'gender' => 'Male',
                't_shirt' => 'XXXL',
                'contact_number' => '2349062840655',
                'altternate_number' => '2348038740884',
                'submitted_date' => '4/1/21 10:21',
                'qr_code' => NULL,
                'status' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            77 =>
            array (
                'id' => 78,
                'title' => 'Mr.',
                'first_name' => 'AKPOTU ',
                'last_name' => 'KINGSLEY',
                'preferred_nickname' => 'KINGZ',
                'email' => 'kingakpo4life@gmail.com',
                'gender' => 'Male',
                't_shirt' => 'Large',
                'contact_number' => '2349062826149',
                'altternate_number' => '2348060077512',
                'submitted_date' => '4/1/21 9:59',
                'qr_code' => NULL,
                'status' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            78 =>
            array (
                'id' => 79,
                'title' => 'Ms.',
                'first_name' => 'Vivienne',
                'last_name' => 'Etoh',
                'preferred_nickname' => 'Vienne',
                'email' => 'vivienne.etoh@kensingtondistillers.com',
                'gender' => 'Female',
                't_shirt' => '10',
                'contact_number' => '2349062844578',
                'altternate_number' => '2348087346563',
                'submitted_date' => '4/1/21 9:55',
                'qr_code' => NULL,
                'status' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            79 =>
            array (
                'id' => 80,
                'title' => 'Ms.',
                'first_name' => 'ARANMOLATE',
                'last_name' => 'MODUPE',
                'preferred_nickname' => 'Timah',
                'email' => 'fatimo.aranmolate@kensingtondistillers.co.uk',
                'gender' => 'Female',
                't_shirt' => '8',
                'contact_number' => '2349062550106',
                'altternate_number' => '2348057944368',
                'submitted_date' => '4/1/21 9:40',
                'qr_code' => NULL,
                'status' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            80 =>
            array (
                'id' => 81,
                'title' => 'Mr.',
                'first_name' => 'Lotachukwu ',
                'last_name' => 'Dike',
                'preferred_nickname' => 'Dickson',
                'email' => 'dikelotachukeu@gmail.com',
                'gender' => 'Male',
                't_shirt' => 'Medium ',
                'contact_number' => '9062537775',
                'altternate_number' => '7060864333',
                'submitted_date' => '4/1/21 9:40',
                'qr_code' => NULL,
                'status' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            81 =>
            array (
                'id' => 82,
                'title' => 'Mr.',
                'first_name' => 'Aiji ',
                'last_name' => 'Raymond ',
                'preferred_nickname' => 'Ray',
                'email' => 'raymondaiji38@yahoo.com',
                'gender' => 'Male',
                't_shirt' => 'Xxl',
                'contact_number' => '18037690936',
                'altternate_number' => '19062840660',
                'submitted_date' => '4/1/21 9:16',
                'qr_code' => NULL,
                'status' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            82 =>
            array (
                'id' => 83,
                'title' => 'Ms.',
                'first_name' => 'Uju',
                'last_name' => 'Okafor ',
                'preferred_nickname' => 'Uju',
                'email' => 'uju.okafor@kensingtondistillers.co.uk',
                'gender' => 'Female',
                't_shirt' => 'Medium ',
                'contact_number' => '2348037095233',
                'altternate_number' => '2349062840656',
                'submitted_date' => '4/1/21 9:13',
                'qr_code' => NULL,
                'status' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            83 =>
            array (
                'id' => 84,
                'title' => 'Mr.',
                'first_name' => 'Chigozie',
                'last_name' => 'Nnebeife',
                'preferred_nickname' => 'SAINT',
                'email' => 'lewisgozzy@yahoo.com',
                'gender' => 'Male',
                't_shirt' => 'XL',
                'contact_number' => '2348134723168',
                'altternate_number' => '2349062844575',
                'submitted_date' => '4/1/21 9:10',
                'qr_code' => NULL,
                'status' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            84 =>
            array (
                'id' => 85,
                'title' => 'Mrs.',
                'first_name' => 'Emmanuel ',
                'last_name' => 'Blessing ',
                'preferred_nickname' => 'Kweke ',
                'email' => 'emmanuelblessing959@gmail.com',
                'gender' => 'Female',
                't_shirt' => 'XL',
                'contact_number' => '23409062537846',
                'altternate_number' => '23408109901970',
                'submitted_date' => '4/1/21 8:22',
                'qr_code' => NULL,
                'status' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            85 =>
            array (
                'id' => 86,
                'title' => 'Ms.',
                'first_name' => 'OBIESIE',
                'last_name' => 'CELESTINE ',
                'preferred_nickname' => 'CELE-BABA ',
                'email' => 'obiesiecelestine@yahoo.com',
                'gender' => 'Male',
                't_shirt' => 'XXl',
                'contact_number' => '2349062844573',
                'altternate_number' => '2348063215304',
                'submitted_date' => '4/1/21 8:18',
                'qr_code' => NULL,
                'status' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            86 =>
            array (
                'id' => 87,
                'title' => 'Mr.',
                'first_name' => 'CHIBUIKE ',
                'last_name' => 'AKUBUEZE ',
                'preferred_nickname' => 'Chubi',
                'email' => 'akubueze.chibuike@kensingtondistillers.co.uk',
                'gender' => 'Male',
                't_shirt' => 'XL',
                'contact_number' => '2349062840659',
                'altternate_number' => '2348038461344',
                'submitted_date' => '4/1/21 6:23',
                'qr_code' => NULL,
                'status' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            87 =>
            array (
                'id' => 88,
                'title' => 'Mr.',
                'first_name' => 'Adelakun ',
                'last_name' => 'Adeolu ',
                'preferred_nickname' => 'Ade',
                'email' => 'deoluadelakun@yahoo.co.uk',
                'gender' => 'Male',
                't_shirt' => 'Large ',
                'contact_number' => '2349062550119',
                'altternate_number' => '2348166556077',
                'submitted_date' => '3/31/21 20:40',
                'qr_code' => NULL,
                'status' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            88 =>
            array (
                'id' => 89,
                'title' => 'Mr.',
                'first_name' => 'Taofeek ',
                'last_name' => 'Lasisi ',
                'preferred_nickname' => 'DamyT',
                'email' => 'taofeek.lasisi@kensingtondistillers.co.uk',
                'gender' => 'Male',
                't_shirt' => 'Large',
                'contact_number' => '2349062844576',
                'altternate_number' => '1',
                'submitted_date' => '3/31/21 20:24',
                'qr_code' => NULL,
                'status' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            89 =>
            array (
                'id' => 90,
                'title' => 'Mr.',
                'first_name' => 'Kenneth',
                'last_name' => 'Elechi Oko',
                'preferred_nickname' => 'Hon. Ken',
                'email' => 'knnthoko@gmail.com',
                'gender' => 'Male',
                't_shirt' => 'Xxl',
                'contact_number' => '2348035608816',
                'altternate_number' => '2349062537240',
                'submitted_date' => '3/31/21 20:22',
                'qr_code' => NULL,
                'status' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            90 =>
            array (
                'id' => 91,
                'title' => 'Mr.',
                'first_name' => 'UBONG ',
                'last_name' => 'INEME',
                'preferred_nickname' => 'Ubong ',
                'email' => 'inem.ubong@kensingtondistillers.co.uk',
                'gender' => 'Male',
                't_shirt' => 'XXL',
                'contact_number' => '2349062537776',
                'altternate_number' => '2349036002007',
                'submitted_date' => '3/31/21 20:17',
                'qr_code' => NULL,
                'status' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            91 =>
            array (
                'id' => 92,
                'title' => 'Ms.',
                'first_name' => 'Anne',
                'last_name' => 'Benjamin ',
                'preferred_nickname' => 'A.J',
                'email' => 'benjaminanne2@gmail.com',
                'gender' => 'Female',
                't_shirt' => 'Size 8',
                'contact_number' => '23409062550113',
                'altternate_number' => '1',
                'submitted_date' => '3/31/21 20:09',
                'qr_code' => NULL,
                'status' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            92 =>
            array (
                'id' => 93,
                'title' => 'Mr.',
                'first_name' => 'Sunday ',
                'last_name' => 'Achukwu ',
                'preferred_nickname' => 'Achuks',
                'email' => 'sunedeh34@gmail.com',
                'gender' => 'Male',
                't_shirt' => 'Medium ',
                'contact_number' => '2348039654541',
                'altternate_number' => '2349062550112',
                'submitted_date' => '3/31/21 19:32',
                'qr_code' => NULL,
                'status' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            93 =>
            array (
                'id' => 94,
                'title' => 'Mr.',
                'first_name' => 'Ezeh',
                'last_name' => 'Michael Onyekachi',
                'preferred_nickname' => 'Mike ',
                'email' => 'Michael.ezeh@kensingtondistillers.co.uk',
                'gender' => 'Male',
                't_shirt' => 'Large ',
                'contact_number' => '2348035545214',
                'altternate_number' => '2348035545214',
                'submitted_date' => '3/31/21 19:25',
                'qr_code' => NULL,
                'status' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            94 =>
            array (
                'id' => 95,
                'title' => 'Mr.',
                'first_name' => 'Isaiah ',
                'last_name' => 'Tope ',
                'preferred_nickname' => 'Temitope ',
                'email' => 'topsynii@gmail.com',
                'gender' => 'Male',
                't_shirt' => 'XL / XXL',
                'contact_number' => '2349062550107',
                'altternate_number' => '2348165056623',
                'submitted_date' => '3/31/21 17:46',
                'qr_code' => NULL,
                'status' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            95 =>
            array (
                'id' => 96,
                'title' => 'Mr.',
                'first_name' => 'Adelaja',
                'last_name' => 'Sanni',
                'preferred_nickname' => 'Rebirth',
                'email' => 'sanni.adelaja@kensingtondistillers.co.uk',
                'gender' => 'Male',
                't_shirt' => 'Xl',
                'contact_number' => '2348160420896',
                'altternate_number' => '+234906 253 7780',
                'submitted_date' => '3/31/21 17:22',
                'qr_code' => NULL,
                'status' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            96 =>
            array (
                'id' => 97,
                'title' => 'Mr.',
                'first_name' => 'Chukwuemeka ',
                'last_name' => 'Ekwuribe ',
                'preferred_nickname' => 'General ',
                'email' => 'chukwuemekaekwuribe@gmail.com',
                'gender' => 'Male',
                't_shirt' => 'Xxl',
                'contact_number' => '2347069211962',
                'altternate_number' => '2349062840662',
                'submitted_date' => '3/31/21 17:18',
                'qr_code' => NULL,
                'status' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            97 =>
            array (
                'id' => 98,
                'title' => 'Mr.',
                'first_name' => 'Peter',
                'last_name' => 'Mbuba',
                'preferred_nickname' => 'Pete',
                'email' => 'peter.mbuba@kensingtondistillers.co',
                'gender' => 'Male',
                't_shirt' => 'XXL',
                'contact_number' => '2348035250519',
                'altternate_number' => '2348022220459',
                'submitted_date' => '3/31/21 16:34',
                'qr_code' => NULL,
                'status' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            98 =>
            array (
                'id' => 99,
                'title' => 'Ms.',
                'first_name' => 'Amarachi ',
                'last_name' => 'Okoji',
                'preferred_nickname' => 'Amara',
                'email' => 'amarachi.okoji@kensingtondistillers.co.uk',
                'gender' => 'Female',
                't_shirt' => 'Medium ',
                'contact_number' => '2349062550118',
                'altternate_number' => '1',
                'submitted_date' => '3/31/21 16:20',
                'qr_code' => NULL,
                'status' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            99 =>
            array (
                'id' => 100,
                'title' => 'Mr.',
                'first_name' => 'IJEOMA',
                'last_name' => 'EDOBOR',
                'preferred_nickname' => 'E.D.O.B.O.R',
                'email' => 'edobor.ijeoma@kensingtondistillers.co.uk',
                'gender' => 'Male',
                't_shirt' => 'XL',
                'contact_number' => '2348038782590',
                'altternate_number' => '1',
                'submitted_date' => '3/31/21 16:18',
                'qr_code' => NULL,
                'status' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            100 =>
            array (
                'id' => 101,
                'title' => 'Mr.',
                'first_name' => 'Oladapo',
                'last_name' => 'Akinola',
                'preferred_nickname' => 'OA',
                'email' => 'oladapo.akinola@kensingtondistillers.co.uk',
                'gender' => 'Male',
                't_shirt' => 'Medium',
                'contact_number' => '2347035358537',
                'altternate_number' => '1',
                'submitted_date' => '3/31/21 14:57',
                'qr_code' => NULL,
                'status' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            101 =>
            array (
                'id' => 102,
                'title' => 'Choose One',
                'first_name' => 'Winifred Titilayo ',
                'last_name' => 'Amakulor',
                'preferred_nickname' => 'Titilayo',
                'email' => 'titilayoamakulor@gmail.com',
                'gender' => 'Female',
                't_shirt' => 'M',
                'contact_number' => '2348091871742',
                'altternate_number' => '2348091871742',
                'submitted_date' => '3/31/21 14:41',
                'qr_code' => NULL,
                'status' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            102 =>
            array (
                'id' => 103,
                'title' => 'Mrs.',
                'first_name' => 'Ijeoma',
                'last_name' => 'Ezennaya ',
                'preferred_nickname' => 'Blessedijay',
                'email' => 'Ijeoma.ezennaya@kensingtondistillers.co.uk',
                'gender' => 'Female',
                't_shirt' => 'L',
                'contact_number' => '2347039292834',
                'altternate_number' => '1',
                'submitted_date' => '3/31/21 14:24',
                'qr_code' => NULL,
                'status' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            103 =>
            array (
                'id' => 104,
                'title' => 'Mr.',
                'first_name' => 'George',
                'last_name' => 'Gordon',
                'preferred_nickname' => 'George',
                'email' => 'george@vanloveren.co.za',
                'gender' => 'Male',
                't_shirt' => 'L',
                'contact_number' => '27768208400',
                'altternate_number' => '27236151340',
                'submitted_date' => '3/31/21 11:42',
                'qr_code' => NULL,
                'status' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            104 =>
            array (
                'id' => 105,
                'title' => 'Mr.',
                'first_name' => 'Funso',
                'last_name' => 'Elubeku',
                'preferred_nickname' => 'Funso',
                'email' => 'funso.elubeku@kensingtondistillers.co.uk',
                'gender' => 'Male',
                't_shirt' => 'Medium',
                'contact_number' => '2348105625401',
                'altternate_number' => '1',
                'submitted_date' => '3/30/21 8:57',
                'qr_code' => NULL,
                'status' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            105 =>
            array (
                'id' => 106,
                'title' => 'Mr.',
                'first_name' => 'Austin',
                'last_name' => 'Mkpayah',
                'preferred_nickname' => 'Boss D',
                'email' => 'austin.mkpayah@kensingtondistillers.co.uk',
                'gender' => 'Male',
                't_shirt' => 'XL',
                'contact_number' => '2348030745437',
                'altternate_number' => '1',
                'submitted_date' => '3/30/21 8:50',
                'qr_code' => NULL,
                'status' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            106 =>
            array (
                'id' => 107,
                'title' => 'Mr.',
                'first_name' => 'Samuel',
                'last_name' => 'Ali',
                'preferred_nickname' => 'Sam',
                'email' => 'sam@gmail.com',
                'gender' => 'Male',
                't_shirt' => 'XL',
                'contact_number' => '2348038165555',
                'altternate_number' => '1',
                'submitted_date' => '3/29/21 14:12',
                'qr_code' => NULL,
                'status' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
        ));


    }
}
